# Generated by Django 4.1.6 on 2023-03-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0002_alter_category_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryid', models.CharField(default='', max_length=70)),
                ('companyname', models.CharField(default='', max_length=70)),
                ('subcategoryname', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=150)),
                ('icon', models.ImageField(upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryid', models.CharField(default='', max_length=70)),
                ('subcategoryid', models.CharField(default='', max_length=70)),
                ('modelyear', models.CharField(default='', max_length=70)),
                ('variant', models.CharField(default='', max_length=70)),
                ('price', models.CharField(default='', max_length=70)),
                ('insured', models.CharField(default='', max_length=70)),
                ('registrationno', models.CharField(default='', max_length=70)),
                ('ownername', models.CharField(default='', max_length=70)),
                ('mobileno', models.CharField(default='', max_length=70)),
                ('colour', models.CharField(default='', max_length=70)),
                ('fueltype', models.CharField(default='', max_length=70)),
                ('no_of_seats', models.CharField(default='', max_length=70)),
                ('transmissiontype', models.CharField(default='', max_length=70)),
                ('picture', models.ImageField(upload_to='static/')),
            ],
        ),
    ]
