# Generated by Django 4.1.6 on 2023-05-21 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0004_administrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userfname', models.CharField(default='', max_length=50)),
                ('userlname', models.CharField(default='', max_length=50)),
                ('mobileno', models.CharField(default='', max_length=15)),
                ('emailid', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
