# Generated by Django 4.1.6 on 2023-05-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0008_agencies_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='agencyid',
            field=models.CharField(default='', max_length=70),
        ),
    ]
