# Generated by Django 4.1.6 on 2023-05-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0009_vehicle_agencyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencies',
            name='city',
            field=models.CharField(default='', max_length=150),
        ),
    ]
