# Generated by Django 4.1.6 on 2023-05-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0010_agencies_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='city',
            field=models.CharField(default='', max_length=150),
        ),
    ]
