# Generated by Django 4.1.6 on 2023-06-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0012_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='picture2',
            field=models.ImageField(default='', upload_to='static/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='picture4',
            field=models.ImageField(default='', upload_to='static/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='picture5',
            field=models.ImageField(default='', upload_to='static/'),
        ),
    ]
