# Generated by Django 4.1.6 on 2023-06-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0013_vehicle_picture2_vehicle_picture4_vehicle_picture5'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='picture3',
            field=models.ImageField(default='', upload_to='static/'),
        ),
    ]
