# Generated by Django 4.1.6 on 2023-06-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0014_vehicle_picture3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='picture2',
            field=models.ImageField(upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='picture3',
            field=models.ImageField(upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='picture4',
            field=models.ImageField(upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='picture5',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
