# Generated by Django 4.1.6 on 2023-06-08 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paynrentapp', '0015_alter_vehicle_picture2_alter_vehicle_picture3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='icon',
        ),
    ]
